apiVersion: v1
kind: Service
metadata:
  name: flipping-cards
  labels:
    app: flipping-cards
spec:
  selector:
    app: flipping-cards
    tier: web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "35.246.89.124"
